/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: 4b4e4ffbda07e528d063adda3f75ae96)
interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
