/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: 9d1d0c734b140ed3c77e310a774e4df6)
interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.svelte-kit/cloudflare/_worker.js");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
