name = "mbta-realtime-worker"
main = "src/index.ts"
compatibility_date = "2026-06-24"

[[durable_objects.bindings]]
name = "VEHICLE_HUB"
class_name = "VehicleHub"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["VehicleHub"]
